#!/bin/bash

NETWORK_SERVICE_NAME="Wi-Fi"
if [ "$#" -ne 1 ]; then
    echo "Argument missing [on/off]"
    exit 0
fi
if [ $1 == "on" ]; then
    echo "Enabling http and https proxy for $NETWORK_SERVICE_NAME"
    networksetup -setwebproxystate "$NETWORK_SERVICE_NAME" on
    networksetup -setsecurewebproxystate "$NETWORK_SERVICE_NAME" on
    networksetup -setsocksfirewallproxystate "$NETWORK_SERVICE_NAME" on
elif [ $1 == "off" ]; then
    echo "Disabling http and https proxy for $NETWORK_SERVICE_NAME"
    networksetup -setwebproxystate "$NETWORK_SERVICE_NAME" off
    networksetup -setsecurewebproxystate "$NETWORK_SERVICE_NAME" off
    networksetup -setsocksfirewallproxystate "$NETWORK_SERVICE_NAME" off
else
    echo "Argument invalid [permitted:on/off]"
fi